
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes
SPLIT_KEYBOARD = yes
LTO_ENABLE = yes

CONSOLE_ENABLE = yes
OS_DETECTION_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
